version: "3"

services:

  # Database.
  db:
    image: mongo:6.0.3
    volumes:
      - .data/db/db/data:/db/data:rw

  # API server (backend).
  api:
    image: docker.io/deepnox/org-oucala-back:0.0.1
    depends_on: [ "db" ]
    links: [ "db" ]
    volumes:
      - ./src/back/src:/app/src:rw
    ports:
      - "8080:8080"

  # Application (frontend).
#  app:
#    image: docker.io/deepnox/org-oucala-app:0.0.1
#    build: src/app/
#    depends_on: [ "db" ]
#    links: [ "db" ]
#    volumes:
#      - ./src/app/src:/app/src:rw
#    ports:
#      - "8080:8080"
