# See: https://blog.silarhi.fr/docker-compose-traefik-https/
version: '3'

services:
  reverse-proxy:
    image: traefik:v2.4
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .data/traefik/traefik.toml:/etc/traefik/traefik.toml
      - .data/traefik/acme.json:/acme.json
    restart: always
    networks:
      - web
networks:
  web:
    external: true
